grav_version: 1.7.18
git:
  repository: https://github.com/23technologies/grav-okeanos.git
  username: 23t-machine-user
  branch: main
  secret_ref: 23t-machine-user-token
hostnames:
  - name: 23technologies.cloud
    www_redirect: true
    use_gardener_dns: false
  - name: 23t.grav.23t-prod.okeanos.dev
    www_redirect: false
    use_gardener_dns: true
