---
apiVersion: v1
kind: Service
metadata:
  name: grav
  annotations:
    - load-balancer.hetzner.cloud/ipv6-disabled: true
spec:
  selector:
    app: grav
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
